#!/usr/bin/env python3
"""Prepare a GROMACS protein-ligand complex with AmberTools/ACPYPE ligand parameters."""

from __future__ import annotations

import argparse
import shutil
import subprocess
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
SKILL_DIR = SCRIPT_DIR.parent


def which(name: str, required: bool = True) -> str:
    path = shutil.which(name)
    if not path and required:
        raise SystemExit(f"Required tool not found in PATH: {name}")
    return path or name


def run(cmd: list[str], log_file: Path, cwd: Path, execute: bool, stdin: str | None = None) -> None:
    with log_file.open("a", encoding="utf-8") as handle:
        handle.write("$ " + " ".join(cmd) + "\n")
        if not execute:
            return
        proc = subprocess.run(
            cmd,
            cwd=str(cwd),
            input=stdin,
            text=True,
            stdout=handle,
            stderr=subprocess.STDOUT,
            check=False,
        )
    if execute and proc.returncode != 0:
        raise SystemExit(f"Command failed; see log: {log_file}")


def clean_protein(input_pdb: Path, output_pdb: Path) -> None:
    waters = {"HOH", "WAT", "SOL", "H2O"}
    with input_pdb.open("r", encoding="utf-8", errors="ignore") as src, output_pdb.open("w", encoding="utf-8") as dst:
        for line in src:
            if not line.startswith(("ATOM", "TER")):
                continue
            if line.startswith("ATOM") and line[17:20].strip() in waters:
                continue
            dst.write(line)
        dst.write("END\n")


def find_acpype_file(outdir: Path, resname: str, suffix: str) -> Path | None:
    candidates = sorted(outdir.glob(f"**/{resname}*{suffix}")) + sorted(outdir.glob(f"**/*{suffix}"))
    return candidates[0] if candidates else None


def read_gro(path: Path) -> tuple[str, list[str], str]:
    lines = path.read_text(encoding="utf-8", errors="ignore").splitlines()
    if len(lines) < 3:
        raise ValueError(f"Invalid GRO file: {path}")
    title = lines[0]
    atoms = lines[2:-1]
    box = lines[-1]
    return title, atoms, box


def merge_gro(protein_gro: Path, ligand_gro: Path, output_gro: Path) -> None:
    title, protein_atoms, box = read_gro(protein_gro)
    _, ligand_atoms, _ = read_gro(ligand_gro)
    atoms = protein_atoms + ligand_atoms
    with output_gro.open("w", encoding="utf-8") as handle:
        handle.write(f"{title} with ligand\n")
        handle.write(f"{len(atoms):5d}\n")
        for atom in atoms:
            handle.write(atom.rstrip() + "\n")
        handle.write(box.rstrip() + "\n")


def patch_topology(topol: Path, ligand_itp: Path, resname: str) -> None:
    text = topol.read_text(encoding="utf-8", errors="ignore")
    include_line = f'#include "{ligand_itp.as_posix()}"'
    if include_line not in text and ligand_itp.name not in text:
        insert_at = text.find("[ system ]")
        if insert_at == -1:
            insert_at = len(text)
        text = text[:insert_at] + f"\n; Ligand topology generated by ACPYPE\n{include_line}\n\n" + text[insert_at:]
    if "[ molecules ]" in text and resname not in text.split("[ molecules ]", 1)[1]:
        text = text.rstrip() + f"\n{resname:<16} 1\n"
    topol.write_text(text, encoding="utf-8")


def copy_mdp_templates(outdir: Path) -> None:
    for name in ["mdp_minim.mdp", "mdp_nvt.mdp", "mdp_npt.mdp", "mdp_md.mdp"]:
        src = SKILL_DIR / "assets" / name
        dst = outdir / name
        if src.exists() and not dst.exists():
            shutil.copy2(src, dst)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--protein", required=True, type=Path, help="Protein PDB.")
    parser.add_argument("--ligand", required=True, type=Path, help="Ligand mol2/sdf/pdb.")
    parser.add_argument("--complex", type=Path, help="Optional protein-ligand complex PDB with final pose.")
    parser.add_argument("--outdir", default="md_setup", type=Path)
    parser.add_argument("--resname", default="LIG")
    parser.add_argument("--ligand-charge", type=int, default=0)
    parser.add_argument("--charge-method", default="bcc", choices=["bcc", "gas", "mul", "resp", "user"])
    parser.add_argument("--gaff", default="gaff2", choices=["gaff", "gaff2"])
    parser.add_argument("--forcefield", default="amber99sb-ildn")
    parser.add_argument("--water", default="tip3p")
    parser.add_argument("--box-type", default="dodecahedron")
    parser.add_argument("--box-distance", type=float, default=1.0)
    parser.add_argument("--ion-conc", type=float, default=0.15)
    parser.add_argument("--solvent-group", default="SOL", help="Group passed to gmx genion.")
    parser.add_argument("--maxwarn", type=int, default=1)
    parser.add_argument("--execute", action="store_true", help="Actually run commands. Without this, only write a plan.")
    args = parser.parse_args()

    args.outdir.mkdir(parents=True, exist_ok=True)
    copy_mdp_templates(args.outdir)
    log_file = args.outdir / "prepare_gromacs_complex.log"
    if log_file.exists():
        log_file.unlink()

    gmx = which("gmx", required=args.execute)
    obabel = which("obabel", required=args.execute)
    antechamber = which("antechamber", required=args.execute)
    parmchk2 = which("parmchk2", required=args.execute)
    acpype = which("acpype", required=args.execute)

    source_protein = args.complex if args.complex else args.protein
    clean_pdb = args.outdir / "protein_clean.pdb"
    clean_protein(source_protein, clean_pdb)

    ligand_mol2 = args.outdir / f"{args.resname}.mol2"
    if args.ligand.suffix.lower() == ".mol2":
        shutil.copy2(args.ligand, ligand_mol2)
    else:
        run([obabel, str(args.ligand), "-O", str(ligand_mol2), "-h", "--gen3d"], log_file, args.outdir, args.execute)

    ligand_gaff = args.outdir / f"{args.resname}_gaff.mol2"
    frcmod = args.outdir / f"{args.resname}.frcmod"
    run(
        [
            antechamber,
            "-i",
            str(ligand_mol2),
            "-fi",
            "mol2",
            "-o",
            str(ligand_gaff),
            "-fo",
            "mol2",
            "-c",
            args.charge_method,
            "-nc",
            str(args.ligand_charge),
            "-at",
            args.gaff,
            "-s",
            "2",
        ],
        log_file,
        args.outdir,
        args.execute,
    )
    run([parmchk2, "-i", str(ligand_gaff), "-f", "mol2", "-o", str(frcmod), "-a", "Y"], log_file, args.outdir, args.execute)
    run([acpype, "-i", str(ligand_gaff), "-b", args.resname, "-n", str(args.ligand_charge), "-a", args.gaff], log_file, args.outdir, args.execute)

    run(
        [
            gmx,
            "pdb2gmx",
            "-f",
            str(clean_pdb),
            "-o",
            "protein_processed.gro",
            "-p",
            "topol.top",
            "-ff",
            args.forcefield,
            "-water",
            args.water,
            "-ignh",
        ],
        log_file,
        args.outdir,
        args.execute,
    )

    protein_gro = args.outdir / "protein_processed.gro"
    ligand_gro = find_acpype_file(args.outdir, args.resname, "_GMX.gro")
    ligand_itp = find_acpype_file(args.outdir, args.resname, "_GMX.itp")
    complex_gro = args.outdir / "complex.gro"
    topol = args.outdir / "topol.top"
    if args.execute:
        if not ligand_gro or not ligand_itp:
            raise SystemExit("ACPYPE output not found; expected *_GMX.gro and *_GMX.itp.")
        merge_gro(protein_gro, ligand_gro, complex_gro)
        patch_topology(topol, ligand_itp.relative_to(args.outdir), args.resname)

    run(
        [
            gmx,
            "editconf",
            "-f",
            "complex.gro",
            "-o",
            "boxed.gro",
            "-bt",
            args.box_type,
            "-d",
            str(args.box_distance),
        ],
        log_file,
        args.outdir,
        args.execute,
    )
    run([gmx, "solvate", "-cp", "boxed.gro", "-cs", "spc216.gro", "-o", "solv.gro", "-p", "topol.top"], log_file, args.outdir, args.execute)
    run(
        [
            gmx,
            "grompp",
            "-f",
            "mdp_minim.mdp",
            "-c",
            "solv.gro",
            "-p",
            "topol.top",
            "-o",
            "ions.tpr",
            "-maxwarn",
            str(args.maxwarn),
        ],
        log_file,
        args.outdir,
        args.execute,
    )
    run(
        [
            gmx,
            "genion",
            "-s",
            "ions.tpr",
            "-o",
            "solv_ions.gro",
            "-p",
            "topol.top",
            "-pname",
            "NA",
            "-nname",
            "CL",
            "-neutral",
            "-conc",
            str(args.ion_conc),
        ],
        log_file,
        args.outdir,
        args.execute,
        stdin=f"{args.solvent_group}\n",
    )
    run([gmx, "make_ndx", "-f", "solv_ions.gro", "-o", "index.ndx"], log_file, args.outdir, args.execute, stdin="q\n")

    print(f"GROMACS setup directory: {args.outdir}")
    print(f"Execution mode: {'execute' if args.execute else 'plan only'}")
    print(f"Log/command plan: {log_file}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
